"""DRCNN channel mixer + AdaCLIP gradient training on lentils multi-file data.

Trains a LearnableChannelMixer (DRCNN-style 1x1 conv reduction 61->16->8->3)
end-to-end with frozen AdaCLIP on the day2/day3/day4 reflectance dataset.

Data layout:
    /mnt/data/day{2,3,4}_reflectance_all/
        Auto_000_*.cu3s   (one frame per file)
        Auto_000.json     (COCO annotations)

Requires a splits CSV (generated by ``cuvis_ai.data.lentils_splits``).

Usage:
    # 1. Generate splits (once)
    uv run python -m cuvis_ai.data.lentils_splits --data-root /mnt/data --output lentils_splits.csv

    # 2. Train
    uv run python examples/adaclip/lentils_drcnn_gradient_training.py \
        data.splits_csv=lentils_splits.csv
"""

from __future__ import annotations

from pathlib import Path

import hydra
import torch
from cuvis_ai.data import MultiFileCu3sDataModule
from cuvis_ai.deciders.binary_decider import QuantileBinaryDecider
from cuvis_ai.node.anomaly_visualization import AnomalyMask, ScoreHeatmapVisualizer
from cuvis_ai.node.channel_mixer import LearnableChannelMixer
from cuvis_ai.node.data import LentilsAnomalyDataNode
from cuvis_ai.node.losses import IoULoss
from cuvis_ai.node.metrics import AnomalyDetectionMetrics
from cuvis_ai.node.monitor import TensorBoardMonitorNode
from cuvis_ai.node.normalization import MinMaxNormalizer
from cuvis_ai.node.pipeline_visualization import PipelineComparisonVisualizer
from cuvis_ai.training import MultiFileTrainRunConfig
from cuvis_ai_core.pipeline.pipeline import CuvisPipeline
from cuvis_ai_core.training import GradientTrainer, StatisticalTrainer
from cuvis_ai_schemas.pipeline import PipelineMetadata
from cuvis_ai_schemas.training import (
    CallbacksConfig,
    EarlyStoppingConfig,
    ModelCheckpointConfig,
    SchedulerConfig,
    TrainingConfig,
)
from loguru import logger
from omegaconf import DictConfig, OmegaConf

from cuvis_ai_adaclip.node import AdaCLIPDetector


@hydra.main(
    config_path="../../configs/",
    config_name="trainrun/lentils_drcnn_adaclip",
    version_base=None,
)
def main(cfg: DictConfig) -> None:
    """DRCNN channel mixer + AdaCLIP training on lentils multi-file data."""

    logger.info("=== Lentils DRCNN Channel Mixer + AdaCLIP Gradient Training ===")

    logger.info("AdaCLIP plugin module imported")

    output_dir = Path(cfg.output_dir)

    # --- Data ---
    datamodule = MultiFileCu3sDataModule(
        splits_csv=cfg.data.splits_csv,
        batch_size=cfg.data.batch_size,
        processing_mode=cfg.data.processing_mode,
    )
    datamodule.setup(stage="fit")

    train_loader = datamodule.train_dataloader()
    first_batch = next(iter(train_loader))
    input_channels = first_batch["cube"].shape[-1]
    logger.info(f"Input channels: {input_channels}")
    logger.info(
        f"Cube dtype={first_batch['cube'].dtype}, shape={first_batch['cube'].shape}, "
        f"min={first_batch['cube'].float().min().item():.4f}, "
        f"max={first_batch['cube'].float().max().item():.4f}"
    )
    if "mask" in first_batch:
        logger.info(
            f"Mask shape={first_batch['mask'].shape}, "
            f"unique={torch.unique(first_batch['mask']).tolist()}"
        )

    # --- Pipeline ---
    pipeline = CuvisPipeline("lentils_drcnn_adaclip_gradient")

    data_node = LentilsAnomalyDataNode(
        normal_class_ids=[0],
    )

    normalizer = MinMaxNormalizer(
        eps=1e-6,
        use_running_stats=True,
        max_initialization_frames=cfg.get("minmax_init_frames", None),
    )

    mixer = LearnableChannelMixer(
        input_channels=input_channels,
        output_channels=3,
        leaky_relu_negative_slope=0.1,
        use_bias=True,
        use_activation=True,
        normalize_output=True,
        init_method="pca",
        eps=1e-6,
        reduction_scheme=[input_channels, 16, 8, 3],
        name="channel_mixer",
    )

    adaclip = AdaCLIPDetector(
        weight_name="pretrained_all",
        backbone="ViT-L-14-336",
        prompt_text="",
        image_size=518,
        prompting_depth=4,
        prompting_length=5,
        gaussian_sigma=4.0,
        use_half_precision=False,
        enable_warmup=False,
        enable_gradients=True,
        name="adaclip",
    )

    iou_loss = IoULoss(
        weight=1.0,
        smooth=1e-6,
        normalize_method="minmax",
        name="iou_loss",
    )

    decider = QuantileBinaryDecider(quantile=0.995, name="decider")
    metrics_node = AnomalyDetectionMetrics(name="metrics_anomaly")

    viz_mask = AnomalyMask(name="mask", channel=30, up_to=5)
    score_viz = ScoreHeatmapVisualizer(name="score_heatmap", normalize_scores=True, up_to=5)
    drcnn_tb_viz = PipelineComparisonVisualizer(
        hsi_channels=[0, 20, 40],
        max_samples=4,
        log_every_n_batches=1,
        name="drcnn_tensorboard_viz",
    )
    tensorboard_node = TensorBoardMonitorNode(
        output_dir=str(output_dir / "tensorboard"),
        run_name=pipeline.name,
    )

    # --- Connect ---
    pipeline.connect(
        (data_node.outputs.cube, normalizer.data),
        (normalizer.normalized, mixer.data),
        (mixer.rgb, adaclip.rgb_image),
        (adaclip.scores, iou_loss.predictions),
        (data_node.outputs.mask, iou_loss.targets),
        (adaclip.scores, decider.logits),
        (adaclip.scores, metrics_node.logits),
        (adaclip.scores, score_viz.scores),
        (adaclip.scores, viz_mask.scores),
        (decider.decisions, metrics_node.decisions),
        (data_node.outputs.mask, metrics_node.targets),
        (decider.decisions, viz_mask.decisions),
        (data_node.outputs.mask, viz_mask.mask),
        (data_node.outputs.cube, viz_mask.cube),
        (data_node.outputs.cube, drcnn_tb_viz.hsi_cube),
        (mixer.rgb, drcnn_tb_viz.mixer_output),
        (data_node.outputs.mask, drcnn_tb_viz.ground_truth_mask),
        (adaclip.scores, drcnn_tb_viz.adaclip_scores),
        (metrics_node.metrics, tensorboard_node.metrics),
        (score_viz.artifacts, tensorboard_node.artifacts),
        (viz_mask.artifacts, tensorboard_node.artifacts),
        (drcnn_tb_viz.artifacts, tensorboard_node.artifacts),
    )

    pipeline.visualize(
        format="render_graphviz",
        output_path=str(output_dir / "pipeline" / f"{pipeline.name}.png"),
        show_execution_stage=True,
    )
    pipeline.visualize(
        format="render_mermaid",
        output_path=str(output_dir / "pipeline" / f"{pipeline.name}.md"),
        direction="LR",
        include_node_class=True,
        wrap_markdown=True,
        show_execution_stage=True,
    )

    # Explicit device placement for faster training + sanity.
    device = "cuda" if torch.cuda.is_available() else "cpu"
    logger.info(f"Moving pipeline to device: {device}")
    pipeline.to(device)
    # Sanity: verify at least one trainable parameter is already on the selected device.
    try:
        first_param = next(mixer.parameters())
        logger.info(f"Sanity (pre-init): mixer first param device={first_param.device}")
    except StopIteration:
        logger.warning("Sanity (pre-init): mixer has no parameters to inspect.")

    # --- Training config ---
    training_cfg = TrainingConfig.from_dict(OmegaConf.to_container(cfg.training, resolve=True))

    if training_cfg.trainer.callbacks is None:
        training_cfg.trainer.callbacks = CallbacksConfig()

    training_cfg.trainer.callbacks.early_stopping.append(
        EarlyStoppingConfig(
            monitor="metrics_anomaly/iou",
            mode="max",
            patience=20,
            min_delta=0.001,
            verbose=True,
        )
    )

    training_cfg.trainer.callbacks.checkpoint = ModelCheckpointConfig(
        dirpath=str(output_dir / "checkpoints"),
        monitor="metrics_anomaly/iou",
        mode="max",
        save_top_k=3,
        save_last=True,
        filename="{epoch:02d}",
        verbose=True,
    )

    if training_cfg.scheduler is None:
        training_cfg.scheduler = SchedulerConfig(
            name="reduce_on_plateau",
            monitor="metrics_anomaly/iou",
            mode="max",
            factor=0.5,
            patience=5,
        )

    # --- Phase 1: Statistical init (PCA for mixer) ---
    if mixer.requires_initial_fit:
        logger.info("Phase 1: Statistical initialization of channel mixer (PCA)...")
        stat_trainer = StatisticalTrainer(pipeline=pipeline, datamodule=datamodule)
        stat_trainer.fit()
    else:
        logger.info("Phase 1: Skipping statistical initialization")

    # --- Phase 2: Unfreeze mixer ---
    unfreeze_node_names = list(cfg.unfreeze_nodes) if "unfreeze_nodes" in cfg else [mixer.name]
    pipeline.unfreeze_nodes_by_name(unfreeze_node_names)
    logger.info(f"Phase 2: Unfrozen nodes: {unfreeze_node_names}")

    # Ensure newly-unfrozen parameters (if any) are on the correct device.
    pipeline.to(device)
    try:
        first_param = next(mixer.parameters())
        logger.info(f"Sanity: mixer first param device={first_param.device}")
    except StopIteration:
        logger.warning("Sanity: mixer has no parameters to inspect.")

    initial_weights = {}
    for name, param in mixer.named_parameters():
        # Keep a CPU copy to make post-training diffs device-agnostic.
        initial_weights[name] = param.detach().clone().cpu()
        logger.info(
            f"  {name}: shape={param.shape}, requires_grad={param.requires_grad}, "
            f"range=[{param.min().item():.4f}, {param.max().item():.4f}]"
        )

    # --- Phase 3: Gradient training ---
    logger.info("Phase 3: Gradient training with IoU loss...")
    grad_trainer = GradientTrainer(
        pipeline=pipeline,
        datamodule=datamodule,
        loss_nodes=[iou_loss],
        metric_nodes=[metrics_node],
        trainer_config=training_cfg.trainer,
        optimizer_config=training_cfg.optimizer,
        monitors=[tensorboard_node],
    )
    grad_trainer.fit()

    # --- Post-training diagnostics ---
    logger.info("=== Mixer Parameters (After Training) ===")
    for name, param in mixer.named_parameters():
        if name in initial_weights:
            diff = (param.detach().cpu() - initial_weights[name]).abs()
            logger.info(
                f"  {name}: range=[{param.min().item():.4f}, {param.max().item():.4f}], "
                f"max_change={diff.max().item():.6f}"
            )

    logger.info("Running validation...")
    val_results = grad_trainer.validate(ckpt_path="last")
    logger.info(f"Validation: {val_results}")

    logger.info("Running test...")
    test_results = grad_trainer.test(ckpt_path="last")
    logger.info(f"Test: {test_results}")

    # --- Save ---
    results_dir = output_dir / "trained_models"
    results_dir.mkdir(parents=True, exist_ok=True)

    pipeline_output_path = results_dir / f"{pipeline.name}.yaml"
    pipeline.save_to_file(
        str(pipeline_output_path),
        metadata=PipelineMetadata(
            name=pipeline.name,
            description=(
                f"DRCNN mixer ({input_channels}->3) + AdaCLIP trained on lentils "
                f"day2/day3/day4 reflectance data."
            ),
            tags=["gradient", "drcnn", "adaclip", "lentils", "channel_mixer"],
            author="cuvis.ai",
        ),
    )

    loss_node_names = [iou_loss.name]
    metric_node_names = [metrics_node.name]
    data_dict = OmegaConf.to_container(cfg.data, resolve=True)

    trainrun_config = MultiFileTrainRunConfig(
        name=cfg.name,
        pipeline=pipeline.serialize(),
        data=data_dict,
        training=training_cfg,
        output_dir=str(output_dir),
        loss_nodes=loss_node_names,
        metric_nodes=metric_node_names,
        freeze_nodes=[],
        unfreeze_nodes=unfreeze_node_names,
    )
    trainrun_output_path = results_dir / f"{cfg.name}_trainrun.yaml"
    trainrun_config.save_to_file(str(trainrun_output_path))
    logger.info(f"Saved TrainRun config: {trainrun_output_path}")

    logger.info("=== Training Complete ===")
    logger.info(f"Pipeline: {pipeline_output_path}")
    logger.info(f"Weights:  {pipeline_output_path.with_suffix('.pt')}")
    logger.info(f"TrainRun: {trainrun_output_path}")
    logger.info(f"TensorBoard: uv run tensorboard --logdir={output_dir / 'tensorboard'}")


if __name__ == "__main__":
    main()
